import Head from "next/head";
import React from "react";

export default function Home({}) {
  return (
      <>
      <Head>
        <title>Next.js with Bun ❤</title>
        <meta name="description" content="Spotify clone - Generated by create next app" />
        <meta name="color-theme" content="#000" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl bg-lime-500 text-black">Hello Spotify</h1>
      </main>
      </>
  );
}
